### ISSUE TITLE
Provide updated JAR file

### ISSUE THREAD

**Issue by hwrdprkns** [mttkay/droid-fu#17]
Hello,

I was just wondering if it was possible to provide an updated JAR file. The one that you currently provide in GitHub is over a year old I believe. The code has been much updated since then. 

Thanks!

**Comment by goranzarkovic** [comment]
I second that motion. 

Thank you :)

**Comment by goranzarkovic** [comment]
Is there any luck that we will have an updated .jar file rolled out soon? 

I would really love to consume the droid-fu library with newest updates and do not have the best knowledge using Maven.

Thanks in advance.

**Comment by Gregadeaux** [comment]
It looks like this isn't being too addressed. Maybe someone with the proper tools could build the jar themselves and link to it here?

**Comment by goranzarkovic** [comment]
Our great friend ysamlan has uploaded an updated .JAR file at his fork site per my request.

Many thanks to him. :) 

It can be obtained on his site under Downloads: https://github.com/ysamlan/droid-fu

**Comment by mttkay** [comment]
Hi,

since there has been no versioned release yet, I don't think it makes sense to provide JAR files for download (in fact I removed the really old one). However, I have updated the README with up-to-date instructions how to build a JAR. Once you have the necessary tooling installed, it's as simple as: `mvn install -DcopyTo=/path/to/your/app/libs` which is easy enough. To get the latest changes before rolling the JAR, do a `git pull`.
