### ISSUE TITLE
transparency of gif's - setCompressedImageFormat

### ISSUE THREAD

**Issue by netpenthe** [mttkay/droid-fu#66]
I see that the method: setCompressedImageFormat used to droidfu/imageLoader/ImageCache.java - https://github.com/kaeppler/droid-fu/issues/6 (this was September 2010)

However this file has now been moved to cachefu and I can no longer find the setCompressedImageFormat

Anyone have any idea how to set this now? Transparencies do not work for me at the moment (with a recent clone of the source)

**Comment by mttkay** [comment]
Hi,

we removed that method because it was not required anymore. What we used to do was basically creating a new bitmap from the image retrieved from the web, which meant we had to specify the image format used to store it. We don't do that anymore; instead, we write and read the raw byte data from and to disk. I don't see how you could lose transparency over this (in fact, we use this in our app and I've never observed that behavior since we closed the bug last year).

**Comment by netpenthe** [comment]
apologise for wasting your time - it was my fault, i had specified a background on the webimageview.

thanks for the great library.

**Comment by netpenthe** [comment]
closing out.

**Comment by mttkay** [comment]
No worries!
